{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "route-planner.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "route-planner.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "route-planner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "route-planner.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ include "route-planner.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ include "route-planner.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
